@enum SquareType OPEN CLOSE GOAL
const Map = [
[OPEN, OPEN, OPEN, OPEN, OPEN]
,[OPEN, CLOSE, CLOSE, OPEN, OPEN]
,[OPEN, CLOSE, GOAL, OPEN, OPEN]
,[OPEN, OPEN, OPEN, OPEN, OPEN]
,[OPEN, CLOSE, OPEN, OPEN, OPEN]
    ,[OPEN, OPEN, OPEN, OPEN, OPEN]]

println(Map[3][3])
